apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: BucketReplicationConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: replication
  name: replication
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: source
    provider: ${aws.central}
    role: ${aws_iam_role.replication.arn}
    rule:
    - destination:
      - bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: destination
        storageClass: STANDARD
      filter:
      - prefix: example
      id: examplerule
      status: Enabled

---

apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: destination
  name: destination
spec:
  forProvider: {}

---

apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: source
  name: source
spec:
  forProvider:
    provider: ${aws.central}

---

apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: source_bucket_acl
  name: source-bucket-acl
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: source
    provider: ${aws.central}

---

apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: BucketVersioning
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: destination
  name: destination
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: destination
    versioningConfiguration:
    - status: Enabled

---

apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: BucketVersioning
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketreplicationconfiguration
  labels:
    testing.upbound.io/example-name: source
  name: source
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: source
    provider: ${aws.central}
    versioningConfiguration:
    - status: Enabled
